# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_mips_core_0_0/zynq_system_mips_core_0_0.xci
# IP: The module: 'zynq_system_mips_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_mips_core_0_0/ip/fp_add/fp_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_mips_core_0_0/ip/fp_mul/fp_mul.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_mul || ORIG_REF_NAME==fp_mul} -quiet] -quiet

# IP: C:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_mips_core_0_0/zynq_system_mips_core_0_0.xci
# IP: The module: 'zynq_system_mips_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_mips_core_0_0/ip/fp_add/fp_add.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_mips_core_0_0/ip/fp_mul/fp_mul.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_mul || ORIG_REF_NAME==fp_mul} -quiet] -quiet
