# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_system/zynq_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system || ORIG_REF_NAME==zynq_system} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_processing_system7_0_0/zynq_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_proc_sys_reset_0_0/zynq_system_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_interconnect_0_0/zynq_system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_axi_interconnect_0_0 || ORIG_REF_NAME==zynq_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_mips_core_0_0/zynq_system_mips_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_mips_core_0_0 || ORIG_REF_NAME==zynq_system_mips_core_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_xlconstant_0_0/zynq_system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_xlconstant_0_0 || ORIG_REF_NAME==zynq_system_xlconstant_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_axi_ahblite_bridge_0_0/zynq_system_axi_ahblite_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_axi_ahblite_bridge_0_0 || ORIG_REF_NAME==zynq_system_axi_ahblite_bridge_0_0} -quiet] -quiet

# IP: bd/zynq_system/ip/zynq_system_auto_pc_0/zynq_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_0 || ORIG_REF_NAME==zynq_system_auto_pc_0} -quiet] -quiet

# XDC: bd/zynq_system/zynq_system_ooc.xdc
