# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_axi_ahblite_bridge_0_0/zynq_system_axi_ahblite_bridge_0_0.xci
# IP: The module: 'zynq_system_axi_ahblite_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_axi_ahblite_bridge_0_0/zynq_system_axi_ahblite_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_system_axi_ahblite_bridge_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_axi_ahblite_bridge_0_0/zynq_system_axi_ahblite_bridge_0_0.xci
# IP: The module: 'zynq_system_axi_ahblite_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryan4/Desktop/CO_LAB/LAB6/practice/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq_system/ip/zynq_system_axi_ahblite_bridge_0_0/zynq_system_axi_ahblite_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_system_axi_ahblite_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
